### ISSUE TITLE
Human bots escape from repairing buildings

### ISSUE THREAD

**Issue by illwieckz** [UnvanquishedAssets/unvanquished_src.dpkdir#1]
Recently, a code was added to help bots escaping places they are stuck in (like holes, crates etc.), this code is simple: if a server see a bot at the exact same place for some time, the bots starts to make random moves and jumps to escape.

There is one legit case for bot not moving without being stuck: humans bot repairing buildings. If the repairing lasts too long, the escape sequence is triggered, so the human bot moves away from the building it was repairing (stopping reparation) then, at the end of the escape sequence, comes back to continue to repair again. 

This bug is very minor, since after the escape sequence the bot comes back to continue the reparation, but we can probably add a condition to the "bot stuck" detection: if the bot is repairing, it's not a valid "stuck" case, do not trigger the escape sequence.

There is probably another legit use case: when an alien bot is healing from Overmind. So we can probably add this other condition too: if the bot is healing from Overmind, do not trigger the escape sequence.

**Comment by Viech** [comment]
Wrong issue tracker? 😄

**Comment by illwieckz** [comment]
I think not:
https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/blob/master/bots/unstick.bt :wink:

**Comment by slipher** [comment]
This was fixed with https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/commit/9e8a86a7c40008ec4cb6aa62933ea497d7eeb9dc.
